[project]
name = "bookloom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "networkx>=3.6.1",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.2",
    "structlog>=25.5.0",
    ]